import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"; 
import {NextUIProvider} from "@nextui-org/react";
import "./globals.css";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
		<body className={`${poppins.className} bg-gradient-to-b from-zinc-800 from-5% bg-zinc-900 min-h-screen`}>
		  <ThemeProvider
			attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
		  >
			{children}
		  </ThemeProvider>
	  </body>
    </html>
  );
}
